### ISSUE TITLE
Enhancement for the StateManager tutorial: Add an update example for the globals

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/collective-soundworks.github.io#9]
While implementing the tutorial https://collective-soundworks.github.io/tutorials/state-manager.html#updating-values-and-subscribing-to-updates I discovered, that it is not trivial to update e.g. the `globals` from the `ControllerExperience` when the shared state is created on server side. The [docs](http://collective-soundworks.github.io/soundworks/client.AbstractExperience.html)  don't provide any further information on this.

**Suggestion:** Add a small example at the end of the tutorial on how to do this to expand the last sentence.

Side note: The "reference" line numbers in the example are quite vulnerable for code changes. Maybe it's better to add a reference code line/block from the code of the lines before the position where the new lines should be added. This then still needs some adjustments when the code changes, but maybe it's a bit more robust.

**Comment by b-ma** [comment]
Many thanks for the review and for the suggestions ! 

(I'm pretty busy right now but hopefully I will be able to have some time to deal with all these open issues in few weeks.)

**Comment by b-ma** [comment]
I guess this is a bit outdated now, let's close 

Thanks again for the feedback!
